version: '3'
services:
  libvirt:
    build: .
    environment:
      LIBVIRT_USER_PASSWORD: '${LIBVIRT_USER_PASSWORD:-}'
      SSH_AUTHORIZED_KEYS: '${SSH_AUTHORIZED_KEYS:-}'
    hostname: libvirt
    ports:
    - ${HOST_SSH_PORT:-2222}:22
    privileged: true
    security_opt:
    - apparmor=unconfined
    volumes:
    - libvirt_conf:/etc/libvirt
    - libvirt_data:/var/lib/libvirt
    - ssh_conf:/etc/ssh
volumes:
  libvirt_conf:
  libvirt_data:
  ssh_conf:
